name: build
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
          check-latest: true

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build -o dist/event-bus

      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: event-bus
          path: dist/event-bus
          if-no-files-found: error
          retention-days: 1
          overwrite: true
